### ISSUE TITLE
Compile on Ubuntu 18.04 failed

### ISSUE THREAD

**Issue by jsvisa** [semigodking/redsocks#107]
When I'm build the redsocks on Ubuntu 18.04 with Linux 4.15.0-43-generic, it failed with the error message as below:

```
Compile with OpenSSL by default. To compile with PolarSSL, run 'make USE_CRYPTO_POLARSSL=true' instead.
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL   -c -o parser.o parser.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL   -c -o main.o main.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL   -c -o redsocks.o redsocks.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL   -c -o log.o log.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL   -c -o direct.o direct.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL   -c -o ipcache.o ipcache.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL   -c -o autoproxy.o autoproxy.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL   -c -o encrypt.o encrypt.c
In file included from encrypt.c:50:0:
encrypt.h:92:18: error: field ‘evp’ has incomplete type
     cipher_evp_t evp;
                  ^~~
encrypt.c: In function ‘enc_key_init’:
encrypt.c:919:17: error: storage size of ‘cipher_info’ isn’t known
     cipher_kt_t cipher_info;
                 ^~~~~~~~~~~
encrypt.c:919:17: warning: unused variable ‘cipher_info’ [-Wunused-variable]
At top level:
encrypt.c:146:12: warning: ‘crypto_stream_xor_ic’ defined but not used [-Wunused-function]
 static int crypto_stream_xor_ic(uint8_t *c, const uint8_t *m, uint64_t mlen,
            ^~~~~~~~~~~~~~~~~~~~
encrypt.c:139:18: warning: ‘supported_ciphers_key_size’ defined but not used [-Wunused-const-variable=]
 static const int supported_ciphers_key_size[] =
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
encrypt.c:134:18: warning: ‘supported_ciphers_iv_size’ defined but not used [-Wunused-const-variable=]
 static const int supported_ciphers_iv_size[] =
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
<builtin>: recipe for target 'encrypt.o' failed
make: *** [encrypt.o] Error 1
```

**Comment by semigodking** [comment]
See #84

**Comment by goldcome** [comment]
```
$ git apply patches/disable-ss.patch
error: patch failed: Makefile:1
error: Makefile: patch does not apply
error: patch failed: redsocks.c:56
error: redsocks.c: patch does not apply
error: patch failed: redudp.c:64
error: redudp.c: patch does not apply
```

**Comment by semigodking** [comment]
make DISABLE_SHADOWSOCKS=true

goldcome <notifications@github.com> 于 2020年3月24日周二 08:45写道：

**Comment by rampageX** [comment]
@semigodking 建议删除 shadowsocks 相关代码，一是它更新比较频繁，二来现在的类似方案也很多，反正都会本地建立 socks5 服务，支持 socks5 就足够了。

**Comment by rampageX** [comment]
@semigodking 建议删除 shadowsocks 相关代码，一是它更新比较频繁，二来现在的类似方案也很多，反正都会本地建立 socks5 服务，支持 socks5 就足够了。

**Comment by semigodking** [comment]
> @semigodking 建议删除 shadowsocks 相关代码，一是它更新比较频繁，二来现在的类似方案也很多，反正都会本地建立 socks5 服务，支持 socks5 就足够了。

是的，但改成默认不编译ss比较好，万一有人要用也还可以用。欢迎PR

**Comment by sonywork** [comment]
我现在在Mac上用的是v2ray和Shadsocks客户端,而且是有多节点，可能需要手动切换。配合一个PF小工具使用https://github.com/sonywork/Brick
